apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample
    app.kubernetes.io/part-of: load-app-5882c035-91dc-42e1-9bbd-d8265bd7d10b
  name: devfile-sampleg6d4
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: devfile-sample
    weight: null
status: {}
